### ISSUE TITLE
执行 gulp compile-es6 时报错

### ISSUE THREAD

**Issue by lmk123** [lmk123/gulp-es6-sass#1]
错误信息：

```
{ [SyntaxError: e:\Work\github\test\package.json: Error while parsing JSON - Unexpected token ﻿]
  name: 'SyntaxError',
  message: 'e:\\Work\\github\\test\\package.json: Error while parsing JSON - Unexpected token ﻿',
  stack: 'SyntaxError: e:\\Work\\github\\test\\package.json: Error while parsing JSON - Unexpected token ﻿\n    at Object.parse (native)\n    at OptionManager.addConfig (e:\\Work\\github\\test\\node_modules\\gulp-es6-sass\\node_modules\\gulp-babel\\node_modules\\babel-core\\lib\\transformation\\file\\options\\option-manager.js:100:62)\n    at OptionManager.findConfigs (e:\\Work\\github\\test\\node_modules\\gulp-es6-sass\\node_modules\\gulp-babel\\node_modules\\babel-core\\lib\\transformation\\file\\options\\option-manager.js:171:32)\n    at OptionManager.init (e:\\Work\\github\\test\\node_modules\\gulp-es6-sass\\node_modules\\gulp-babel\\node_modules\\babel-core\\lib\\transformation\\file\\options\\option-manager.js:229:12)\n    at File.initOptions (e:\\Work\\github\\test\\node_modules\\gulp-es6-sass\\node_modules\\gulp-babel\\node_modules\\babel-core\\lib\\transformation\\file\\index.js:147:75)\n    at new File (e:\\Work\\github\\test\\node_modules\\gulp-es6-sass\\node_modules\\gulp-babel\\node_modules\\babel-core\\lib\\transformation\\file\\index.js:137:22)\n    at Pipeline.transform (e:\\Work\\github\\test\\node_modules\\gulp-es6-sass\\node_modules\\gulp-babel\\node_modules\\babel-core\\lib\\transformation\\pipeline.js:164:16)\n    at DestroyableTransform._transform (e:\\Work\\github\\test\\node_modules\\gulp-es6-sass\\node_modules\\gulp-babel\\index.js:30:20)\n    at DestroyableTransform.Transform._read (e:\\Work\\github\\test\\node_modules\\gulp-es6-sass\\node_modules\\gulp-babel\\node_modules\\through2\\node_modules\\readable-stream\\lib\\_stream_transform.js:172:10)\n    at DestroyableTransform.Transform._write (e:\\Work\\github\\test\\node_modules\\gulp-es6-sass\\node_modules\\gulp-babel\\node_modules\\through2\\node_modules\\readable-stream\\lib\\_stream_transform.js:160:12)',
  fileName: 'e:\\Work\\github\\test\\src\\test.es6',
  showStack: false,
  showProperties: false,
  plugin: 'gulp-babel' }
```

**Comment by lmk123** [comment]
我是在 webstorm 里执行这个任务的，错误信息里面显示的是 `Unexpected token -`（最后面有个中划线），但是写在 github 里却没有了。我抱着试一试的心情，右键点击 `package.json` 并选择 `Remove BOM` 之后就好了。。
